version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-express-container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules